name: 'pnpm installation'
description: 'Install and audit dependencies for pnpm'
inputs:
  cache: # id of input
    description: 'The location of the pnpm cache'
    required: true
    default: '.pnpm-store'

runs:
  using: 'composite'
  steps:
    - name: enable corepack
      run: corepack enable
      shell: bash

    - name: install pnpm
      run: pnpm --version
      shell: bash

    - name: setup pnpm config
      run: pnpm config set store-dir ${{ inputs.cache }}
      shell: bash

    - name: install dependencies
      run: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 pnpm install
      shell: bash

    - name: build packages
      run: pnpm remirror-cli build
      shell: bash
