version: '2'
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 6
  file-lines:
    config:
      threshold: 750
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 25
  method-lines:
    config:
      threshold: 75
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 6

exclude_patterns:
  - 'support/'
  - '@remirror/api-documenter/' # TODO remove from exclude once package is completed
  - 'e2e/'
  - 'docs/'
  - '**/data/'
  - '**/node_modules/'
  - '**/__tests__/'
  - '**/__mocks__/'
  - '**/*.d.ts'
  - '**/*.dts.ts'
  - '**/jest.*'
