import React from 'react';
import {
  FaAngleUp,
  FaAsterisk,
  FaBold,
  FaCode,
  FaHeading,
  FaImage,
  FaIndent,
  FaItalic,
  FaLink,
  FaListOl,
  FaListUl,
  FaOutdent,
  FaParagraph,
  FaQuoteLeft,
  FaRedo,
  FaStrikethrough,
  FaSubscript,
  FaSuperscript,
  FaTable,
  FaUnderline,
  FaUndo,
} from 'react-icons/fa';

export default {
  em: <FaItalic />,
  italic: <FaItalic />,
  strong: <FaBold />,
  bold: <FaBold />,
  code: <FaCode />,
  subscript: <FaSubscript />,
  superscript: <FaSuperscript />,
  underline: <FaUnderline />,
  strikethrough: <FaStrikethrough />,
  link: <FaLink />,
  paragraph: <FaParagraph />,
  heading: <FaHeading />,
  blockquote: <FaQuoteLeft />,
  code_block: <FaCode />,
  ordered_list: <FaListOl />,
  bullet_list: <FaListUl />,
  image: <FaImage />,
  table: <FaTable />,
  footnote: <FaAsterisk />,
  undo: <FaUndo />,
  redo: <FaRedo />,
  lift: <FaOutdent />,
  join_up: <FaAngleUp />,
  before: <FaIndent />,
  after: <FaIndent />,
};
