/* AUTOGENERATED FILE - DO NOT EDIT */
export type CategoriesType = Record<
  | 'symbols'
  | 'people'
  | 'animals_and_nature'
  | 'food_and_drink'
  | 'activity'
  | 'travel_and_places'
  | 'objects'
  | 'flags',
  string
>;
const categories: CategoriesType = {
  symbols: 'Symbols',
  people: 'People',
  animals_and_nature: 'Animals & Nature',
  food_and_drink: 'Food & Drink',
  activity: 'Activity',
  travel_and_places: 'Travel & Places',
  objects: 'Objects',
  flags: 'Flags',
};

export default categories;
