export {
  EDITOR_CLASS_NAME,
  EDITOR_CLASS_SELECTOR,
  EMPTY_NODE,
  EMPTY_PARAGRAPH_NODE,
  ExtensionPriority,
  ExtensionTag,
  ExtensionType,
  LEAF_NODE_REPLACING_CHARACTER,
  ManagerPhase,
  MarkGroup,
  NON_BREAKING_SPACE_CHAR,
  NULL_CHARACTER,
  NodeGroup,
  RemirrorIdentifier,
  SELECTED_NODE_CLASS_NAME,
  SELECTED_NODE_CLASS_SELECTOR,
  ZERO_WIDTH_SPACE_CHAR,
  __INTERNAL_REMIRROR_IDENTIFIER_KEY__,
} from './core-constants';
export { ErrorConstant } from './error-constants';
